name: habitsbegone
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
 



  cupertino_icons: ^1.0.8
  get: ^4.7.2
  shared_preferences: ^2.5.3
  http: ^1.3.0
  toast: ^0.3.0
  fluttertoast: ^8.2.12
  loading_animation_widget: ^1.3.0
  google_fonts: ^6.3.0
  flutter_svg: ^2.2.0
  flutter_launcher_icons: ^0.13.1 # check pub.dev for latest
  scroll_wheel_selector: ^0.0.2
  square_in_app_payments: ^1.7.11
  cloud_functions: ^6.0.2
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  firebase_messaging: ^16.0.2
  file_picker: ^10.3.3
  video_player: ^2.10.0
  video_thumbnail: ^0.5.6
  open_filex: ^4.7.0
  url_launcher: ^6.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_foreground: "assets/images/app_icon.png" # optionals  
  

  
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
